const projects_es = [
  {
    id: 1,
    title: "Light Project",
    category: "Video1",
    image: "p1",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 2,
    title: "Light Project",
    category: "Video2",
    image: "p2",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 3,
    title: "Light Project",
    category: "Video3",
    image: "p3",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 4,
    title: "Light Project",
    category: "Video4",
    image: "p4",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 5,
    title: "Light Project",
    category: "Video5",
    image: "p5",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 6,
    title: "Light Project",
    category: "Video6",
    image: "p6",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 7,
    title: "Light Project",
    category: "Video7",
    image: "p7",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 8,
    title: "Light Project",
    category: "Video8",
    image: "p8",
    url: "https://www.carlosbaso.com/",
  },
  {
    id: 9,
    title: "Light Project",
    category: "Video9",
    image: "p9",
    url: "https://www.carlosbaso.com/",
  },
];
export { projects_es };
